### ISSUE TITLE
firmware ncp-uart-sw_6.10.3_115200.gbl & later versions don't work in Openhab whis dongle ZB-GW04 v1.2 

### ISSUE THREAD

**Issue by frfstu** [xsp1989/zigbeeFirmware#37]
![openhab](https://user-images.githubusercontent.com/87616721/223945762-fcc778f0-18fc-4332-a921-099d23b0a1a0.png)
![IMG_20230309_093559](https://user-images.githubusercontent.com/87616721/223943183-22f35111-e57c-4a69-bd9f-6492c25c610f.jpg)
![IMG_20230309_093846](https://user-images.githubusercontent.com/87616721/223943207-cfa60e4e-ddff-479c-89df-bb8a34c4813d.jpg)
![IMG_20230309_094003](https://user-images.githubusercontent.com/87616721/223943219-70209e8f-eb68-40ee-98f2-33a6e3f1e821.jpg)
![IMG_20230309_094544](https://user-images.githubusercontent.com/87616721/223943227-7b787266-68a8-41d8-9326-3f80c43fccba.jpg)
After update & upgrade Openhab to latest version software, installing bindings zigbee & install z2m i'm get this problem:

1. 2023-03-08 18:24:49.199 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 

java.lang.NullPointerException: null

	at com.zsmartsystems.zigbee.dongle.ember.EmberNcp.getConfiguration(EmberNcp.java:457) ~[?:?]

	at com.zsmartsystems.zigbee.dongle.ember.internal.EmberStackConfiguration.getConfiguration(EmberStackConfiguration.java:72) ~[?:?]

	at com.zsmartsystems.zigbee.dongle.ember.ZigBeeDongleEzsp.initialize(ZigBeeDongleEzsp.java:439) ~[?:?]

	at com.zsmartsystems.zigbee.ZigBeeNetworkManager.initialize(ZigBeeNetworkManager.java:418) ~[?:?]

	at org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler.initialiseZigBee(ZigBeeCoordinatorHandler.java:431) ~[?:?]

	at org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler.lambda$2(ZigBeeCoordinatorHandler.java:557) ~[?:?]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]

	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]

	at java.lang.Thread.run(Thread.java:829) [?:?]

2. 2023-03-08 18:24:24.576 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'zigbee:coordinator_ember:49a0e318d9' changed from INITIALIZING to ONLINE

2023-03-08 18:24:25.772 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Smart_home_server_Memory_UsedPercent' changed from 60 % to 60.1 %

2023-03-08 18:24:26.206 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Smart_home_server_Memory_Used' changed from 587 MiB to 586 MiB

2023-03-08 18:24:27.346 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Smart_home_server_Cpu_Load' changed from 59.9 % to 58.2 %

2023-03-08 18:24:27.613 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Smart_home_server_Memory_UsedPercent' changed from 60.1 % to 60.3 %

==> /var/log/openhab/openhab.log <==

2023-03-08 18:24:29.921 [WARN ] [e.ember.internal.ash.AshFrameHandler] - ASH: ERROR received (code 6). Disconnecting.

==> /var/log/openhab/events.log <==

2023-03-08 18:24:29.937 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'zigbee:coordinator_ember:49a0e318d9' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR)

2023-03-08 18:24:30.712 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Smart_home_server_Cpu_Load' changed from 58.2 % to 15.9 %

==> /var/log/openhab/openhab.log <==

2023-03-08 18:24:30.937 [INFO ] [bee.handler.ZigBeeCoordinatorHandler] - ZigBee dongle inactivity timer. Reinitializing ZigBee

3. Zigbee2MQTT page on port 8081 not started
4. I'm testing all available firmware versions including it https://github.com/xsp1989/zigbeeFirmware/tree/master/firmware/Zigbee3.0_Dongle-NoSigned/RCPMultiPAN 
All versions not usables fo this dongle! My smarthome downgradeble to stupid & no controlled (no work nothink)!!!
a curtain..

**Comment by frfstu** [comment]
Hello and thanks for your reply! The only thing I managed in openhab was to
add a coordinator to Binding Zigbee! The coordinator was added, it didn’t
give errors, but it’s impossible to work with it (you can only see data
transfer statistics), it didn’t work to connect devices to the zigbee
network (at least for me personally)! If it's not difficult, please tell me
how to manually install the required (working version) of zigbee2mqtt
through the command line terminal! I studied a very large number of
different instructions but did not find the answer to this question.

ср, 22 мар. 2023 г., 15:32 xsp1989 ***@***.***>:
